import { v } from 'convex/values';
import { mutation, query } from './_generated/server';

/**
 * Animation upload + recording.
 *
 * MANUAL-FIRST BY DESIGN. Clips are generated by hand (fal.ai playground) and
 * uploaded via scripts/upload-animation.ts until the character bible and beat
 * timing are locked on the pilot category. `generationJobs` stays unused until
 * then. See specs/content-pipeline.md rule 9.
 *
 * The metadata args are REQUIRED even for manual uploads. With automation the
 * job record captures them for free; by hand they exist only in your head, and
 * a clip you cannot reproduce is a clip you cannot fix.
 */

/**
 * Step 1 of upload. Returns a short-lived URL the script POSTs the file to.
 * Convex hands back a storageId which is passed to `recordAnimation`.
 */
export const generateUploadUrl = mutation({
  args: {},
  returns: v.string(),
  handler: async (ctx) => {
    // TODO(auth): restrict to admin identities before this is reachable in
    // any deployed environment. Currently open — dev seeding only.
    return await ctx.storage.generateUploadUrl();
  },
});

/**
 * Step 2. Records the clip against a phrase.
 *
 * NOTE: phraseId, NOT a translation id. Animations are language-independent —
 * one clip serves all 22 languages. See schema.ts structural decision 1.
 *
 * Always lands as `draft`. Publishing is a separate, deliberate act
 * (CLAUDE.md rule 14) — nothing generative auto-publishes, even when you
 * generated it yourself and are about to approve your own work.
 */
export const recordAnimation = mutation({
  args: {
    phraseId: v.id('phrases'),
    storageId: v.id('_storage'),
    keyframeStorageIds: v.optional(v.array(v.id('_storage'))),

    // Reproducibility metadata — required.
    model: v.string(),
    ratePerSecond: v.number(),
    durationSec: v.number(),
    prompt: v.string(),
    seed: v.optional(v.number()),
    attempt: v.number(),
  },
  returns: v.id('animations'),
  handler: async (ctx, args) => {
    const phrase = await ctx.db.get(args.phraseId);
    if (!phrase) throw new Error(`No phrase ${args.phraseId}`);

    if (args.durationSec < 7 || args.durationSec > 12) {
      // Under ~7s there is no room for three beats; over ~12s the model drifts.
      throw new Error(
        `Duration ${args.durationSec}s is outside the 7–12s window. ` +
          `See specs/branding-and-voice.md.`,
      );
    }

    return await ctx.db.insert('animations', {
      phraseId: args.phraseId,
      storageId: args.storageId,
      keyframeStorageIds: args.keyframeStorageIds ?? [],
      model: args.model,
      ratePerSecond: args.ratePerSecond,
      durationSec: args.durationSec,
      prompt: args.prompt,
      seed: args.seed,
      attempt: args.attempt,
      status: 'draft',
      approvedBy: undefined,
      approvedAt: undefined,
    });
  },
});

/**
 * The approval gate. Deliberately separate from recordAnimation.
 *
 * Before calling this, apply the acceptance test from
 * specs/branding-and-voice.md: MUTE THE AUDIO AND HIDE THE SUBTITLE. If a
 * learner cannot infer roughly what the phrase means, the clip is decoration,
 * not teaching — reject it.
 */
export const approveAnimation = mutation({
  args: {
    animationId: v.id('animations'),
    approvedBy: v.id('users'),
  },
  returns: v.null(),
  handler: async (ctx, args) => {
    // TODO(auth): derive approver from the auth identity, never an argument.
    const animation = await ctx.db.get(args.animationId);
    if (!animation) throw new Error(`No animation ${args.animationId}`);

    // Supersede any previously live clip for this phrase — one live clip each.
    const existing = await ctx.db
      .query('animations')
      .withIndex('by_phrase', (q) => q.eq('phraseId', animation.phraseId))
      .collect();

    for (const a of existing) {
      if (a._id !== args.animationId && a.status === 'live') {
        await ctx.db.patch(a._id, { status: 'archived' });
      }
    }

    await ctx.db.patch(args.animationId, {
      status: 'live',
      approvedBy: args.approvedBy,
      approvedAt: Date.now(),
    });
    return null;
  },
});

/** Admin review queue. Returns non-live clips — never exposed to the app. */
export const listPendingReview = query({
  args: {},
  handler: async (ctx) => {
    const drafts = await ctx.db
      .query('animations')
      .withIndex('by_status', (q) => q.eq('status', 'draft'))
      .collect();

    return Promise.all(
      drafts.map(async (a) => ({
        ...a,
        url: await ctx.storage.getUrl(a.storageId),
        phrase: await ctx.db.get(a.phraseId),
      })),
    );
  },
});
