import { v } from 'convex/values';
import { internalMutation, mutation, query } from './_generated/server';
import { requireCurrentUserDoc } from './lib/currentUser';

/**
 * Animation upload + recording.
 *
 * Originally manual-first: clips were generated by hand (fal.ai playground)
 * and uploaded via scripts/upload-animation.ts while the character bible and
 * beat timing were still being locked on the pilot category (Greetings). See
 * specs/content-pipeline.md rule 9.
 *
 * That pilot is done. `packages/backend/convex/fal/animations.ts` now drives
 * this same `recordAnimation` mutation programmatically — a Convex
 * `internalAction` that calls fal.ai directly instead of a human copying URLs
 * out of the playground. `scripts/upload-animation.ts` still works and is
 * useful for one-off manual fixes/re-uploads, but it is no longer the only
 * path in. `generationJobs` is still unused by either path.
 *
 * The metadata args are REQUIRED either way. With automation the job record
 * captures them for free; by hand they exist only in your head, and a clip
 * you cannot reproduce is a clip you cannot fix.
 */

/**
 * Step 1 of upload. Returns a short-lived URL the script POSTs the file to.
 * Convex hands back a storageId which is passed to `recordAnimation`.
 */
export const generateUploadUrl = mutation({
  args: {},
  returns: v.string(),
  handler: async (ctx) => {
    // Requires an authenticated, onboarded app user — rejects anonymous
    // calls. This is NOT an admin-role gate: any signed-in user can reach
    // this today. Role-based restriction (admin-only) is deferred to phase
    // 10 / apps/admin, which does not exist yet — there is no role concept
    // anywhere in schema.ts to gate on. Tighten this once that lands.
    await requireCurrentUserDoc(ctx);
    return await ctx.storage.generateUploadUrl();
  },
});

/**
 * Same as `generateUploadUrl`, for the trusted CLI/ops path only.
 *
 * `internalMutation`s are unreachable from any client (no spoofing surface —
 * the exact thing the auth check above guards against), only from
 * `bunx convex run`, the scheduler, or another Convex function — so this is
 * safe without an identity check. Exists because `scripts/upload-animation.ts`
 * uses a bare `ConvexHttpClient` with no session (it's a one-off manual
 * re-upload tool run by the project owner, not an app screen), and the
 * platform does not let a public HTTP client call `internal.*` functions
 * directly — the script shells out to `convex run` for this one step instead.
 */
export const generateUploadUrlInternal = internalMutation({
  args: {},
  returns: v.string(),
  handler: async (ctx) => {
    return await ctx.storage.generateUploadUrl();
  },
});

/**
 * Step 2. Records the clip against a phrase.
 *
 * NOTE: phraseId, NOT a translation id. Animations are language-independent —
 * one clip serves all 22 languages. See schema.ts structural decision 1.
 *
 * Always lands as `draft`. Publishing is a separate, deliberate act
 * (CLAUDE.md rule 14) — nothing generative auto-publishes, even when you
 * generated it yourself and are about to approve your own work.
 */
export const recordAnimation = mutation({
  args: {
    phraseId: v.id('phrases'),
    storageId: v.id('_storage'),
    keyframeStorageIds: v.optional(v.array(v.id('_storage'))),

    // Reproducibility metadata — required.
    model: v.string(),
    ratePerSecond: v.number(),
    durationSec: v.number(),
    prompt: v.string(),
    seed: v.optional(v.number()),
    attempt: v.number(),
  },
  returns: v.id('animations'),
  handler: async (ctx, args) => {
    const phrase = await ctx.db.get(args.phraseId);
    if (!phrase) throw new Error(`No phrase ${args.phraseId}`);

    if (args.durationSec < 7 || args.durationSec > 12) {
      // Under ~7s there is no room for three beats; over ~12s the model drifts.
      throw new Error(
        `Duration ${args.durationSec}s is outside the 7–12s window. ` +
          `See specs/branding-and-voice.md.`,
      );
    }

    return await ctx.db.insert('animations', {
      phraseId: args.phraseId,
      storageId: args.storageId,
      keyframeStorageIds: args.keyframeStorageIds ?? [],
      model: args.model,
      ratePerSecond: args.ratePerSecond,
      durationSec: args.durationSec,
      prompt: args.prompt,
      seed: args.seed,
      attempt: args.attempt,
      status: 'draft',
      approvedBy: undefined,
      approvedAt: undefined,
    });
  },
});

/**
 * The approval gate. Deliberately separate from recordAnimation.
 *
 * Before calling this, apply the acceptance test from
 * specs/branding-and-voice.md: MUTE THE AUDIO AND HIDE THE SUBTITLE. If a
 * learner cannot infer roughly what the phrase means, the clip is decoration,
 * not teaching — reject it.
 */
export const approveAnimation = mutation({
  args: {
    animationId: v.id('animations'),
  },
  returns: v.null(),
  handler: async (ctx, args) => {
    // Approver is derived from the auth identity, never a client argument —
    // approvedBy used to be a raw `v.id('users')` arg, trivially spoofable.
    const approver = await requireCurrentUserDoc(ctx);

    const animation = await ctx.db.get(args.animationId);
    if (!animation) throw new Error(`No animation ${args.animationId}`);

    // Supersede any previously live clip for this phrase — one live clip each.
    const existing = await ctx.db
      .query('animations')
      .withIndex('by_phrase', (q) => q.eq('phraseId', animation.phraseId))
      .collect();

    for (const a of existing) {
      if (a._id !== args.animationId && a.status === 'live') {
        await ctx.db.patch(a._id, { status: 'archived' });
      }
    }

    await ctx.db.patch(args.animationId, {
      status: 'live',
      approvedBy: approver._id,
      approvedAt: Date.now(),
    });
    return null;
  },
});

/**
 * Same approval logic, for the trusted CLI/ops path — see
 * `generateUploadUrlInternal`'s doc comment for why this exists.
 * `approvedBy` is an explicit arg here rather than derived from an identity
 * because `bunx convex run` (deploy-key auth) has no app-user session to
 * derive one from; unlike the public `approveAnimation`, this is safe
 * because `internalMutation`s have no client-facing spoofing surface at all.
 */
export const approveAnimationInternal = internalMutation({
  args: {
    animationId: v.id('animations'),
    approvedBy: v.id('users'),
  },
  returns: v.null(),
  handler: async (ctx, args) => {
    const animation = await ctx.db.get(args.animationId);
    if (!animation) throw new Error(`No animation ${args.animationId}`);

    const existing = await ctx.db
      .query('animations')
      .withIndex('by_phrase', (q) => q.eq('phraseId', animation.phraseId))
      .collect();

    for (const a of existing) {
      if (a._id !== args.animationId && a.status === 'live') {
        await ctx.db.patch(a._id, { status: 'archived' });
      }
    }

    await ctx.db.patch(args.animationId, {
      status: 'live',
      approvedBy: args.approvedBy,
      approvedAt: Date.now(),
    });
    return null;
  },
});

/**
 * Resolve a single animation's storage blobs to signed URLs, regardless of
 * status. `listPendingReview` only surfaces `draft` rows by design (it's the
 * review queue) — this is for verifying a specific row (e.g. one already
 * `live`) directly, by id, from tooling.
 */
export const getSignedUrls = query({
  args: { animationId: v.id('animations') },
  handler: async (ctx, args) => {
    const animation = await ctx.db.get(args.animationId);
    if (!animation) return null;
    return {
      status: animation.status,
      videoUrl: await ctx.storage.getUrl(animation.storageId),
      keyframeUrls: await Promise.all(
        animation.keyframeStorageIds.map((id) => ctx.storage.getUrl(id)),
      ),
    };
  },
});

/** Admin review queue. Returns non-live clips — never exposed to the app. */
export const listPendingReview = query({
  args: {},
  handler: async (ctx) => {
    const drafts = await ctx.db
      .query('animations')
      .withIndex('by_status', (q) => q.eq('status', 'draft'))
      .collect();

    return Promise.all(
      drafts.map(async (a) => ({
        ...a,
        url: await ctx.storage.getUrl(a.storageId),
        phrase: await ctx.db.get(a.phraseId),
      })),
    );
  },
});
